CREATE OR REPLACE PACKAGE AUTOHANDLER IS 
    FUNCTION KONYV_BY_ID(ID NUMBER) RETURN KONYVEK%ROWTYPE;
    FUNCTION GET_AVG_PRICE RETURN NUMBER;
    PROCEDURE ADD_CAR(RSZ CHAR,TIPUS VARCHAR2,SZIN VARCHAR2,EVJARAT NUMBER, AR NUMBER);
    PROCEDURE DELETE_CAR(RSZ CHAR);
END;

CREATE OR REPLACE PACKAGE BODY AUTOHANDLER IS 
    FUNCTION KONYV_BY_ID(ID NUMBER) RETURN KONYVEK%ROWTYPE IS KONYV KONYVEK%ROWTYPE;
    
    BEGIN
        SELECT KID,AR,CIM,KATEGORIA,SZERZO,KIADOID INTO KONYV FROM KONYVEK WHERE KID= ID;
        RETURN KONYV;
    END;
    
    FUNCTION GET_AVG_PRICE RETURN NUMBER IS AVG_KONYVEK NUMBER;
    
    BEGIN
        SELECT AVG(AR) INTO AVG_KONYVEK FROM KONYVEK;
        RETURN AVG_KONYVEK;
    END;
    
    procedure ADD_CAR(rsz char, tipus varchar2, szin varchar2, evjarat number, ar number) is
    begin
        insert into auto values(rsz,tipus,szin,evjarat,ar);
    end;
   
    procedure delete_car(rsz char) is
    begin
        delete auto where rsz=rsz;
    end;
END;

SELECT autohandler.GET_AVG_PRICE FROM dual;

SELECT autohandler.ADD_CAR('VALAMI','vALAMI','KEK',2001,2341) FROM DUAL;
