CREATE OR REPLACE TRIGGER NEV BEFORE/AFTER/INSTEAD OF INSERT OR UPDATE OR DELETE ON AUTO FOR EACH ROW WHEN
DECLARE

BEGIN

END;

CREATE OR REPLACE TRIGGER DELETE_ON_AUTO AFTER DELETE ON AUTO FOR EACH ROW

DECLARE
    MSG CHAR(50) := CONCAT(:OLD.RSZ ' RENDSZÁMÚ AUTÓ TÖRÖLVE');
BEGIN
    DBMS_OUTPUT.PUT_LINE(MSG);
END;

DELETE FROM AUTO;