CREATE OR REPLACE TRIGGER CHECKTRIGGER BEFORE UPDATE ON KONYVEK FOR EACH ROW
BEGIN
    IF NOT ((:NEW.AR / (:OLD.AR / 100)) >= 80 AND (:NEW.AR / (:OLD.AR / 100)) <= 120) THEN
        IF :OLD.AR < :NEW.AR THEN
            :NEW.AR := :OLD.AR * 1.2;
        END IF;
        IF :NEW.AR < :OLD.AR THEN
            :NEW.AR := :OLD.AR * 0.8;
        END IF;
        DBMS_OUTPUT.PUT_LINE('A MÓDOSÍTÁS MÉRTÉKE MEGHALADJA A 20%-OT, EZÉRT KORLÁTOZVA LETT!');
    END IF;
END;

UPDATE KONYVEK SET AR = 1000000000 WHERE KID = 3;