DECLARE
    k_ID KIADOK.KIADOID%TYPE;
    k_NEV KIADOK.NEV%TYPE;
    k_EV kiadok.kiadaseve%TYPE;
    CURSOR LEKERDEZES IS SELECT KIADOID, NEV, KIADASEVE FROM KIADOK;
BEGIN
    OPEN LEKERDEZES;
    LOOP
        FETCH LEKERDEZES INTO k_ID, k_NEV, k_EV;
        EXIT WHEN LEKERDEZES%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(k_ID || ' ' || k_NEV || ' ' || k_EV);
    END LOOP;
    CLOSE LEKERDEZES;
END;

set serveroutput on