----Kiado tabla rekord felvitele
CREATE OR REPLACE PROCEDURE FELVISZKIADO (KIADID INT, NEV VARCHAR2, KIADASEVE VARCHAR2) IS 
EXSISTERROR EXCEPTION;
rows_found number;

BEGIN
    SELECT COUNT(*) INTO ROWS_FOUND FROM KIADOK WHERE KIADOID= KIADID;
    
    IF ROWS_FOUND != 0 THEN RAISE EXSISTERROR;
    ELSE
        INSERT INTO KIADOK VALUES(KIADID,NEV,KIADASEVE);
    END IF;
EXCEPTION
    WHEN exsisterror THEN
    dbms_output.put_line('Ez az azonosító már létezik!');
END FELVISZKIADO;

---Konyvek tabla rekord felvitele
CREATE OR REPLACE PROCEDURE FELVISZKONYV(KID IN konyvek.kid%TYPE,AR IN konyvek.ar%TYPE, CIM IN KONYVEK.cim%TYPE, KATEGORIA IN konyvek.kategoria%TYPE, SZERZO IN konyvek.szerzo%TYPE, KIADOID IN konyvek.kiadoid%TYPE)
IS EXSISTERROR EXCEPTION;
rows_found number;

BEGIN
    SELECT COUNT(*) INTO ROWS_FOUND FROM KONYVEK WHERE KID= KID;
    
    IF ROWS_FOUND != 0 THEN RAISE EXSISTERROR;
    ELSE
        INSERT INTO KONYVEK VALUES(KID,AR,CIM,KATEGORIA,SZERZO,KIADOID);
    END IF;
EXCEPTION
    WHEN exsisterror THEN
    dbms_output.put_line('Ez az azonosító már létezik!');
END FELVISZKONYV;

---Kiadok tabla modositasa
CREATE OR REPLACE PROCEDURE MODOSIT (ID INT, NAME VARCHAR2) IS 
        notexsisterror exception;
		nameequalerror exception;
		rows_found number;
        current_name char(20);
BEGIN
    SELECT COUNT(*) INTO ROWS_FOUND FROM KIADOK WHERE KIADOID = ID;

			IF ROWS_FOUND !=0 THEN
				SELECT NEV INTO CURRENT_NAME FROM KIADOK WHERE KIADOID = KIADOID;
			END IF;

			IF ROWS_FOUND = 0 THEN RAISE NOTEXSISTERROR;
			ELSIF 
                NAME = CURRENT_NAME THEN RAISE NAMEEQUALERROR;
			ELSE
				UPDATE KIADOK SET NEV = NAME WHERE KIADOID = KIADOID;
			END IF;
		EXCEPTION
			WHEN NOTEXSISTERROR THEN
			DBMS_OUTPUT.PUT_LINE('ILYEN AZONOSÍTÓJÚ TERMÉK NEM LÉTEZIK!');
			WHEN NAMEEQUALERROR THEN
			DBMS_OUTPUT.PUT_LINE('UGYANAZ A NÉV VAN MEGADVA!');
END MODOSIT;

---Konyvek tabla modositasa
CREATE OR REPLACE PROCEDURE MODOSITKONYV(ID INT ,PRICE INT) IS
NOTEXSISTERROR EXCEPTION;
PRICEISNOTVALID EXCEPTION;
ROWS_FOUND NUMBER;

BEGIN

    SELECT COUNT(*) INTO ROWS_FOUND FROM KONYVEK WHERE KID= KID;
			IF ROWS_FOUND = 0 THEN RAISE NOTEXSISTERROR;
			ELSIF 
                 PRICE < 1 THEN RAISE PRICEISNOTVALID;
			ELSE
				UPDATE KONYVEK SET AR = PRICE WHERE KID = ID;
			END IF;
		EXCEPTION
			WHEN NOTEXSISTERROR THEN
			DBMS_OUTPUT.PUT_LINE('ILYEN AZONOSÍTÓJÚ TERMÉK NEM LÉTEZIK!');
			WHEN PRICEISNOTVALID THEN
            DBMS_OUTPUT.PUT_LINE('A MEGADOTT ÁR NEM MEGFELEL?!');
END MODOSITKONYV;

---Konyvek tabla rekordok torlese
CREATE OR REPLACE PROCEDURE TOROLKONYV(ID INT) IS
NOTEXSISTERROR EXCEPTION;
rows_found number;

BEGIN
   SELECT COUNT(*) INTO ROWS_FOUND FROM KONYVEK WHERE KID= ID;
    
    IF ROWS_FOUND = 0 THEN RAISE NOTEXSISTERROR;
    ELSE
        DELETE FROM KONYVEK WHERE KID = ID;
    END IF;
    EXCEPTION
			WHEN NOTEXSISTERROR THEN
			DBMS_OUTPUT.PUT_LINE('ILYEN AZONOSÍTÓJÚ TERMÉK NEM LÉTEZIK!');
END TOROLKONYV;

---Kiadok tabla rekordok torlese
CREATE OR REPLACE PROCEDURE TOROLKIADO(ID INT) IS
NOTEXSISTERROR EXCEPTION;
rows_found number;

BEGIN
   SELECT COUNT(*) INTO ROWS_FOUND FROM KIADOK WHERE KIADOID= ID;
    
    IF ROWS_FOUND = 0 THEN RAISE NOTEXSISTERROR;
    ELSE
        DELETE FROM KIADOK WHERE KIADOID = ID;
    END IF;
    EXCEPTION
			WHEN NOTEXSISTERROR THEN
			DBMS_OUTPUT.PUT_LINE('ILYEN AZONOSÍTÓJÚ TERMÉK NEM LÉTEZIK!');
END TOROLKIADO;

---Eljarasok futtatasa
EXECUTE FELVISZKIADO(8,'VALAMI','VALAMIKOR');
EXECUTE FELVISZKONYV(1,1450,'VALAMI','LÍRA','ÉN',8);
EXECUTE MODOSIT(1,'SZAR');
EXECUTE MODOSITKONYV(1,2000);
EXECUTE TOROLKONYV(1);
EXECUTE TOROLKIADO(8);

SELECT * FROM KIADOK;

SELECT * FROM DATA_LOG;

SELECT * FROM KONYVEK;