CREATE OR REPLACE TRIGGER KIADOKKTRIGGER
BEFORE INSERT OR DELETE OR UPDATE ON KIADOK FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO DATA_LOG VALUES(CURRENT_TIMESTAMP, 'BESZÚRÁS', 'KIADOK');
    END IF;
    IF DELETING THEN
        INSERT INTO DATA_LOG VALUES(CURRENT_TIMESTAMP, 'TÖRLÉS', 'KIADOK');
    END IF;
    IF UPDATING THEN
        INSERT INTO DATA_LOG VALUES(CURRENT_TIMESTAMP, 'MÓDOSÍTÁS', 'KIADOK');
    END IF;
END;