CREATE OR REPLACE TRIGGER KONYVVEKTRIGGER
BEFORE INSERT OR DELETE OR UPDATE ON KONYVEK FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO DATA_LOG VALUES(CURRENT_TIMESTAMP, 'BESZÚRÁS', 'KONYVEK');
    END IF;
    IF DELETING THEN
        INSERT INTO DATA_LOG VALUES(CURRENT_TIMESTAMP, 'TÖRLÉS', 'KONYVEK');
    END IF;
    IF UPDATING THEN
        INSERT INTO DATA_LOG VALUES(CURRENT_TIMESTAMP, 'MÓDOSÍTÁS', 'KONYVEK');
    END IF;
END;